// Package wrapper: Node.js HTTPS_PROXY shim.
//
// Why this file exists
// ────────────────────
// Node's built-in HTTP stacks ignore HTTPS_PROXY by default:
//
//	node:https (raw)             → never uses proxy env
//	globalThis.fetch (undici)    → needs explicit dispatcher
//	axios / node-fetch / Octokit → only if their inner agent is patched
//
// MCP servers shipped by Anthropic and the community are overwhelmingly
// Node.js. Without intervention, our wrapper sets HTTPS_PROXY and the
// child happily ignores it, talking to api.github.com directly with
// the proxy token in the Authorization header — which then 401s, AND
// in a more permissive future could leak the proxy token to the open
// internet.
//
// What the shim does
// ──────────────────
// When the wrap command is started with --node-shim, mcp-gate writes a
// small JS file to its temp dir and sets:
//
//	NODE_OPTIONS=--require=<temp-shim>
//
// The shim runs before the MCP server's main module and:
//
//	1. Replaces https.globalAgent with a custom HttpsProxyAgent that
//	   tunnels every connection through HTTPS_PROXY via HTTP CONNECT.
//	2. Replaces globalThis.fetch with a thin wrapper that uses the same
//	   proxy agent for all outbound requests.
//
// Patching https.globalAgent covers raw https, axios, node-fetch v2/v3,
// Octokit, and all other clients that respect Node's default agent.
// Native fetch (undici) is patched at the public API level; if a user's
// code creates its own undici Dispatcher manually, that path remains
// the user's responsibility.
package wrapper

// nodeShimSrc is the JS the wrapper writes to disk and loads via
// NODE_OPTIONS=--require=. It deliberately uses no external npm packages
// (so users don't have to `npm install` anything) — only Node built-ins.
const nodeShimSrc = `// Auto-generated by mcp-gate. Do not edit.
// Patches Node HTTP clients to respect HTTPS_PROXY when --node-shim is set.
'use strict';

const proxyURL = process.env.HTTPS_PROXY || process.env.https_proxy ||
                 process.env.HTTP_PROXY  || process.env.http_proxy;
if (!proxyURL) return;

const tls   = require('node:tls');
const net   = require('node:net');
const https = require('node:https');
const http  = require('node:http');

const u = new URL(proxyURL);
const proxyHost = u.hostname;
const proxyPort = parseInt(u.port || '80', 10);

// CONNECT proxy via Node's http.request: lets Node parse the CONNECT
// response correctly and hands us back the underlying socket plus any
// "head" bytes that arrived in the same chunk as the response. We
// unshift the head so TLS sees them, then start TLS on the socket.
function connectThroughProxy(opts, cb) {
  const targetHost = opts.host || opts.hostname;
  const targetPort = opts.port || 443;

  const req = http.request({
    host: proxyHost,
    port: proxyPort,
    method: 'CONNECT',
    path: targetHost + ':' + targetPort,
    headers: { Host: targetHost + ':' + targetPort },
    agent: false,
  });
  req.once('connect', (res, sock, head) => {
    if (res.statusCode !== 200) {
      cb(new Error('mcp-gate node-shim: proxy CONNECT ' + res.statusCode));
      sock.destroy();
      return;
    }
    if (head && head.length > 0) sock.unshift(head);
    const tlsSock = tls.connect({
      ...opts,
      socket: sock,
      servername: targetHost,
      ALPNProtocols: opts.ALPNProtocols || ['http/1.1'],
    });
    cb(null, tlsSock);
  });
  req.once('error', cb);
  req.end();
}

class HttpsProxyAgent extends https.Agent {
  createConnection(opts, cb) { connectThroughProxy(opts, cb); }
}
class HttpProxyAgent extends http.Agent {
  createConnection(opts, cb) {
    const sock = net.connect(proxyPort, proxyHost);
    sock.once('connect', () => cb(null, sock));
    sock.once('error', cb);
  }
}

// keepAlive: false — empirically with our CONNECT-tunneled sockets,
// keepAlive holds the response stream open past 'end', causing user
// code that awaits 'end' to hang forever. One connection per request
// is the safe default; MCP servers rarely make enough requests for
// this to matter.
https.globalAgent = new HttpsProxyAgent({ keepAlive: false });
http.globalAgent  = new HttpProxyAgent({ keepAlive: false });

// Native fetch (undici) doesn't respect global Agent. Wrap it with a
// version that uses our agent via the lower-level https.request path.
const _originalFetch = globalThis.fetch;
globalThis.fetch = async function shimmedFetch(input, init) {
  const url = (input instanceof URL) ? input :
              (typeof input === 'string' ? new URL(input) :
               new URL(input.url));
  if (url.protocol !== 'https:' && url.protocol !== 'http:') {
    return _originalFetch ? _originalFetch(input, init) : Promise.reject(new Error('unsupported scheme'));
  }
  return new Promise((resolve, reject) => {
    const isHttps = url.protocol === 'https:';
    const lib = isHttps ? https : http;
    const headers = {};
    if (init && init.headers) {
      const h = init.headers;
      if (h instanceof Headers) {
        h.forEach((v, k) => { headers[k] = v; });
      } else if (Array.isArray(h)) {
        for (const [k, v] of h) headers[k] = v;
      } else {
        Object.assign(headers, h);
      }
    }
    if (!headers['host'] && !headers['Host']) headers['Host'] = url.host;

    const req = lib.request({
      method: (init && init.method) || 'GET',
      host:   url.hostname,
      port:   url.port || (isHttps ? 443 : 80),
      path:   url.pathname + url.search,
      headers,
      // Force our patched globalAgent (lib.request defaults to it but
      // some callers override).
      agent:  isHttps ? https.globalAgent : http.globalAgent,
    }, (res) => {
      const chunks = [];
      res.on('data', (c) => chunks.push(c));
      res.on('end', () => {
        const body = Buffer.concat(chunks);
        // Build a minimal Response. Native Response/Headers are global.
        const respHeaders = new Headers();
        for (const [k, v] of Object.entries(res.headers)) {
          if (Array.isArray(v)) v.forEach((vv) => respHeaders.append(k, vv));
          else if (v != null) respHeaders.set(k, String(v));
        }
        resolve(new Response(body, {
          status: res.statusCode,
          statusText: res.statusMessage,
          headers: respHeaders,
        }));
      });
    });
    req.on('error', reject);
    if (init && init.body) req.write(init.body);
    req.end();
  });
};
`
